import type { NextPage } from "next";
import Head from "next/head";
import styled from 'styled-components';

const Hello = styled.div`
    font-size: 100px;
`;

const Home: NextPage = () => {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hello>
            Hello, XQUARE
        </Hello>
    </div>
  );
};

export default Home;
